# Generated by Django 5.0.1 on 2025-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorActivities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipsey',
            name='retailmap',
        ),
        migrations.AddField(
            model_name='lipsey',
            name='map',
            field=models.TextField(blank=True, db_column='Map', null=True),
        ),
        migrations.AlterField(
            model_name='cwr',
            name='cwr_part_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
