# Generated by Django 5.0.1 on 2025-09-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorActivities', '0002_vendors_api_access_id_vendors_api_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwr',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fragrancex',
            name='sku',
            field=models.CharField(blank=True, db_column='SKU', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lipsey',
            name='sku',
            field=models.CharField(blank=True, db_column='Sku', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rsr',
            name='sku',
            field=models.CharField(blank=True, db_column='SKU', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ssi',
            name='sku',
            field=models.CharField(blank=True, db_column='SKU', db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
