# Generated by Django 5.0.1 on 2025-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorActivities', '0003_alter_cwr_sku_alter_fragrancex_sku_alter_lipsey_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
