# Generated by Django 5.0.1 on 2025-10-13 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorActivities', '0004_vendors_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='api_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='integration_type',
            field=models.CharField(choices=[('default', 'Default Integration'), ('requested', 'Requested Integration')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='vendors',
            name='request_type',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Request'), ('force', 'Force Request')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
