# Generated by Django 5.0.1 on 2025-12-05 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorEnrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalproducttable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalproducttable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
