# Generated by Django 5.0.1 on 2025-08-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorActivities', '0002_remove_lipsey_retailmap_lipsey_map_and_more'),
        ('vendorEnrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwrupdate',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fragrancexupdate',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lipseyupdate',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsrupdate',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ssiupdate',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zandersupdate',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='stock_maximum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='stock_minimum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ssiupdate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorActivities.zanders'),
        ),
    ]
