# Generated by Django 5.0.1 on 2025-12-29 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorActivities', '0005_vendors_api_details_vendors_description_and_more'),
        ('vendorEnrollment', '0002_generalproducttable_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('vendor', 'user', 'identifier'), name='unique_enrollment_per_user_vendor_identifier'),
        ),
    ]
