# Generated by Django 5.0.1 on 2026-02-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorEnrollment', '0003_enrollment_unique_enrollment_per_user_vendor_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwrupdate',
            name='msrp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fragrancexupdate',
            name='msrp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lipseyupdate',
            name='msrp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsrupdate',
            name='msrp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ssiupdate',
            name='msrp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zandersupdate',
            name='msrp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
