# Generated by Django 5.0.1 on 2025-08-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tier",
            old_name="max_orders",
            new_name="included_orders",
        ),
        migrations.RenameField(
            model_name="tier",
            old_name="max_integrations",
            new_name="included_vendors",
        ),
        migrations.RemoveField(
            model_name="tier",
            name="max_sku",
        ),
        migrations.RemoveField(
            model_name="tier",
            name="tier",
        ),
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tier",
            name="advanced_analytics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tier",
            name="api_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tier",
            name="branded_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tier",
            name="dedicated_success_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tier",
            name="extra_order_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="tier",
            name="extra_sku_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="tier",
            name="extra_store_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="tier",
            name="extra_vendor_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="tier",
            name="included_stores",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tier",
            name="inventory_sync",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tier",
            name="store_sku_limit",
            field=models.PositiveIntegerField(default=250000),
        ),
        migrations.AddField(
            model_name="tier",
            name="white_label_branding",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="accounts.tier",
            ),
        ),
    ]
