# Generated by Django 5.0.1 on 2025-09-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_max_orders_tier_included_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImages/'),
        ),
        migrations.DeleteModel(
            name='UploadedUserProfileImage',
        ),
    ]
