# Generated by Django 5.2.3 on 2025-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="fixed_percentage_markup",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="inventorymodel",
            name="market_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="inventorymodel",
            name="mpn",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="inventorymodel",
            name="woocommerce_category_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="inventorymodel",
            name="category",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="inventorymodel",
            name="ebay_item_id",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
