# Generated by Django 5.2.3 on 2025-10-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0002_inventorymodel_fixed_percentage_markup_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorymodel",
            old_name="ebay_item_id",
            new_name="market_item_id",
        ),
    ]
