# Generated by Django 5.2.3 on 2025-10-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0003_rename_ebay_item_id_inventorymodel_market_item_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorymodel",
            old_name="woocommerce_category_name",
            new_name="woo_category_name",
        ),
    ]
