# Generated by Django 5.2.3 on 2025-11-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventoryApp",
            "0004_rename_woocommerce_category_name_inventorymodel_woo_category_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="upc",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
