# Generated by Django 5.2.3 on 2025-11-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0005_alter_inventorymodel_upc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="upc",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
