# Generated by Django 5.2.3 on 2025-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0006_alter_inventorymodel_upc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="category",
            field=models.TextField(null=True),
        ),
    ]
