# Generated by Django 5.2.3 on 2025-12-05 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0007_alter_inventorymodel_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="category",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="inventorymodel",
            name="upc",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name="UpdateLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_name", models.TextField()),
                ("vendor_name", models.TextField()),
                ("updated_items", models.CharField(max_length=25)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                ("log_description", models.TextField(null=True)),
                (
                    "inventory_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventoryApp.inventorymodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
