# Generated by Django 5.2.3 on 2025-12-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0008_alter_inventorymodel_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="updatelogmodel",
            old_name="inventory_id",
            new_name="inventory",
        ),
        migrations.RenameField(
            model_name="updatelogmodel",
            old_name="updated_items",
            new_name="updated_item",
        ),
    ]
