# Generated by Django 5.2.3 on 2025-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0009_rename_inventory_id_updatelogmodel_inventory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="updatelogmodel",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
