# Generated by Django 5.2.3 on 2025-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0010_inventorymodel_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="ends_status",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
