# Generated by Django 5.2.3 on 2025-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0011_inventorymodel_ends_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="market_item_url",
            field=models.TextField(null=True),
        ),
    ]
