# Generated by Django 5.2.3 on 2025-12-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0013_alter_inventorymodel_mpn"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="vendor_identifier",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
