# Generated by Django 5.2.3 on 2025-12-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0014_inventorymodel_vendor_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="manual_map",
            field=models.BooleanField(default=False),
        ),
    ]
