# Generated by Django 5.2.3 on 2026-01-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0015_inventorymodel_manual_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="last_updated",
            field=models.DateTimeField(),
        ),
    ]
