# Generated by Django 5.2.3 on 2026-01-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0016_alter_inventorymodel_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="last_updated",
            field=models.DateTimeField(null=True),
        ),
    ]
