# Generated by Django 5.2.3 on 2026-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0017_alter_inventorymodel_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="map",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
