# Generated by Django 5.2.3 on 2026-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0018_inventorymodel_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="market_item_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
