# Generated by Django 5.2.3 on 2026-03-01 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0019_alter_inventorymodel_market_item_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UpdateLogModel",
            new_name="MarketPlaceUpdateLog",
        ),
        migrations.RenameField(
            model_name="marketplaceupdatelog",
            old_name="updated_item",
            new_name="updated_sku",
        ),
        migrations.CreateModel(
            name="PriceQuantityUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_name", models.TextField()),
                ("vendor_name", models.TextField()),
                ("updated_sku", models.CharField(max_length=25)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("log_description", models.TextField(null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventoryApp.inventorymodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
