# Generated by Django 5.2.3 on 2026-04-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryApp", "0020_rename_updatelogmodel_marketplaceupdatelog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="model",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
