# Generated by Django 5.0.1 on 2025-12-21 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.JSONField()),
                ('recipients', models.JSONField()),
                ('category', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('trigger_type', models.CharField(choices=[('immediately', 'Immediately'), ('recurring', 'Recurring'), ('custom', 'Custom')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('interval_days', 'Every X Days'), ('interval_hours', 'Every X Hours')], max_length=20, null=True)),
                ('recurring_interval', models.PositiveIntegerField(blank=True, help_text='Used when frequency is interval_days or interval_hours', null=True)),
                ('recurring_start', models.DateTimeField(blank=True, null=True)),
                ('recurring_end', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(default='in_app', max_length=20)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificationApp.notificationtemplate')),
            ],
        ),
    ]
