# Generated by Django 5.2.3 on 2025-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersonebaymodel",
            name="localizeAspects",
            field=models.TextField(null=True),
        ),
    ]
