# Generated by Django 5.2.3 on 2025-12-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderApp", "0002_alter_ordersonebaymodel_localizeaspects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordersonebaymodel",
            old_name="ebayItemId",
            new_name="itemMarketStatus",
        ),
        migrations.RenameField(
            model_name="ordersonebaymodel",
            old_name="itemEbayStatus",
            new_name="marketItemId",
        ),
        migrations.AddField(
            model_name="ordersonebaymodel",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
