# Generated by Django 5.0.1 on 2025-12-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_rename_ebayitemid_ordersonebaymodel_itemmarketstatus_and_more'),
        ('vendorEnrollment', '0002_generalproducttable_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersonebaymodel',
            name='market_name',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.CreateModel(
            name='VendorOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(db_index=True, max_length=50)),
                ('vendor_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='created', max_length=30)),
                ('reference_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='vendorEnrollment.enrollment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='orderApp.ordersonebaymodel')),
            ],
        ),
    ]
