# Generated by Django 5.0.1 on 2025-12-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0004_ordersonebaymodel_market_name_vendororderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororderlog',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
