# Generated by Django 5.0.1 on 2026-01-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0005_alter_vendororderlog_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersonebaymodel',
            name='lineItemId',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
