# Generated by Django 5.0.1 on 2026-02-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0006_ordersonebaymodel_lineitemid'),
        ('vendorEnrollment', '0003_enrollment_unique_enrollment_per_user_vendor_identifier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendororderlog',
            constraint=models.UniqueConstraint(fields=('order', 'vendor'), name='unique_order_vendor'),
        ),
    ]
