# Generated by Django 5.0.1 on 2026-02-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0007_vendororderlog_unique_order_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderlog',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
