# Generated by Django 5.0.1 on 2026-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0008_vendororderlog_hold_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderlog',
            name='fulfillment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
