# Generated by Django 5.2.3 on 2025-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaceApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceenronment",
            name="wc_auto_populate_msrp",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="marketplaceenronment",
            name="wc_consumer_key",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceenronment",
            name="wc_consumer_secret",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceenronment",
            name="wc_consumer_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceenronment",
            name="wc_map_enforcement",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="marketplaceenronment",
            name="wc_product_status",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedproductimage",
            name="image_url",
            field=models.ImageField(max_length=1000, upload_to=""),
        ),
    ]
